debug: false
server:
  port: 8100

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    url: jdbc:mariadb://localhost:3306/
    schemas: book_service
    user: root
    password: root