debug: false
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    url: jdbc:mariadb://localhost:3306/
    schemas: cambio_service
    user: root
    password: root